baseurl: 'devflair-research-web'
exclude: ['README.md']
permalink: pretty
title: 'DevFlair'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo.png"
  desktop: "images/logo/logo.png"
  desktop_height: "100px"
footer:
  copyright_text: 'DevFlair &copy; 2022'

seo:
  meta_og_title: "DevFlair"
  meta_og_type: "website"

collections:
  scopes:
    output: true
  products:
    output: true
  presentations:
    output: true
  milestones:
    output: true
  documents:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables